version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: gostudy
      TZ: Asia/Shanghai
    ports:
    - 5678:5432
    volumes:
    - ./data/postgres-data:/var/lib/postgresql/data
  empty_classroom_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: gostudy
      TZ: Asia/Shanghai
    ports:
    - 5678:5432
    volumes:
    - ./data/postgres-data:/var/lib/postgresql/data
  Nginx:
    depends_on:
    - apiservice
    - api_empty
    - admin
    build: ./nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/cert:/cert
    environment:
      TZ: Asia/Shanghai
  Redis:
    image: redis:6
    command: redis-server --requirepass passwd
    ports:
    - 6379:6379
